name: oghref_model
description: Object standarized definition with parser interface for constructing rich information of given URL among various metadata protocols.
version: 3.5.1
repository: https://github.com/rk0cc/oghref/tree/main/model
issue_tracker: https://github.com/rk0cc/oghref/issues
funding:
  - https://github.com/sponsors/rk0cc
topics:
  - fetch
  - http
  - metadata
environment: 
  sdk: '>=3.3.0 <4.0.0'
dependencies: 
  meta: ^1.9.1
  http: ^1.1.0
  html: '>=0.15.4 <1.0.0'
  mime_dart: ^3.0.0
  path: ^1.8.3
  web: ^0.5.1
dev_dependencies: 
  lints: ">=3.0.0 <5.0.0"
  test: ^1.24.8
  