name: oghref_model
description: Object standarized definition with parser interface for constructing rich information of given URL among various metadata protocols.
version: 5.0.0
repository: https://github.com/rk0cc/oghref/tree/main/model
issue_tracker: https://github.com/rk0cc/oghref/issues
funding:
  - https://github.com/sponsors/rk0cc
topics:
  - fetch
  - http
  - metadata
environment: 
  sdk: ^3.8.0
resolution: workspace
dependencies: 
  meta: ^1.15.0
  http: ^1.5.0
  html: '>=0.15.6 <1.0.0'
  path: ^1.9.1
  web: ^1.1.1
  fetch_client: ^1.1.4
  mime_dart: ^3.0.0
dev_dependencies: 
  lints: ^5.0.0
  test: ^1.25.15
  