name: oghref_model
description: Object standarized definition with parser interface for constructing rich information of given URL among various metadata protocols.
version: 1.0.0-beta.1
repository: https://github.com/rk0cc/oghref/tree/main/model
issue_tracker: https://github.com/rk0cc/oghref/issues
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  meta: ^1.9.1
  http: ^1.1.0
  html: '>=0.15.4 <1.0.0'
dev_dependencies: 
  lints: ^2.1.1
  test: ^1.24.6
