version: 2
updates:
  - directory: /model
    open-pull-requests-limit: 3
    package-ecosystem: pub
    schedule:
      time: "15:00"
      timezone: Asia/Hong_Kong
      interval: monthly
  - directory: /builder
    package-ecosystem: pub
    schedule:
      time: "15:00"
      timezone: Asia/Hong_Kong
      interval: monthly
  - directory: /media_control
    open-pull-requests-limit: 3
    package-ecosystem: pub
    schedule:
      time: "15:00"
      timezone: Asia/Hong_Kong
      interval: monthly
  - directory: /widgets/cupertino
    package-ecosystem: pub
    schedule:
      time: "15:00"
      timezone: Asia/Hong_Kong
      interval: monthly
  - directory: /widgets/fluent
    package-ecosystem: pub
    schedule:
      time: "15:00"
      timezone: Asia/Hong_Kong
      interval: monthly
  - directory: /widgets/material
    package-ecosystem: pub
    schedule:
      time: "15:00"
      timezone: Asia/Hong_Kong
      interval: monthly
  - directory: /
    package-ecosystem: github-actions
    open-pull-requests-limit: 2
    schedule:
      time: "15:00"
      timezone: Asia/Hong_Kong
      interval: monthly
