name: oghref_fluent
description: Fluent themed widget for generating rich information link from URL.
version: 1.0.2
repository: https://github.com/rk0cc/oghref/tree/main/widgets/fluent
issue_tracker: https://github.com/rk0cc/oghref/issues
funding:
  - https://github.com/sponsors/rk0cc
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'
screenshots:
  - description: Screenshot of OgHref Fluent example
    path: screenshots/oghref_fluent.png
dependencies: 
  flutter:
    sdk: flutter
  oghref_builder: ^3.1.0
  oghref_media_control: ^3.0.5
  oghref_model: ^2.1.2
  meta: ^1.9.1
  media_kit: ^1.1.10+1
  fluent_ui: ^4.8.1
  fluentui_system_icons: ^1.1.222
dev_dependencies: 
  flutter_lints: ^3.0.1
flutter: 