name: oghref_fluent
description: Fluent themed widget for generating rich information link from URL.
version: 5.0.0
repository: https://github.com/rk0cc/oghref/tree/main/widgets/fluent
issue_tracker: https://github.com/rk0cc/oghref/issues
funding:
  - https://github.com/sponsors/rk0cc
screenshots:
  - description: Screenshot of OgHref Fluent example
    path: screenshots/oghref_fluent.png
topics:
  - web
  - link
  - graph
  - http
  - fluent
environment:
  sdk: ^3.8.0
  flutter: '>=3.32.0'
resolution: workspace
dependencies: 
  flutter:
    sdk: flutter
  oghref_builder: ^5.0.0
  oghref_media_control: ^5.0.0
  oghref_model: ^5.0.0
  meta: ^1.15.0
  media_kit: ^1.2.0
  fluent_ui: ^4.12.0
  fluentui_system_icons: ^1.1.273
  smooth_page_indicator: ^1.2.1
dev_dependencies: 
  flutter_lints: ^5.0.0
