name: oghref_media_control
description: Additional package for providing mixin to build widget for playing multimedia resources
version: 4.0.1
repository: https://github.com/rk0cc/oghref/tree/main/media_control
issue_tracker: https://github.com/rk0cc/oghref/issues
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'
dependencies: 
  flutter:
    sdk: flutter
  media_kit: ^1.1.10+1
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  meta: ^1.9.1
  http: ^1.1.0
  collection: ^1.18.0
  web: ^0.5.1
dev_dependencies: 
  flutter_lints: ^3.0.1
flutter: 