name: oghref_media_control
description: Additional package for providing mixin to build widget for playing multimedia resources
version: 5.0.0
repository: https://github.com/rk0cc/oghref/tree/main/media_control
issue_tracker: https://github.com/rk0cc/oghref/issues
environment:
  sdk: ^3.8.0
  flutter: '>=3.32.0'
resolution: workspace
dependencies: 
  flutter:
    sdk: flutter
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_video: ^1.0.6
  meta: ^1.15.0
  http: ^1.5.0
  collection: ^1.19.1
  web: ^1.1.1
  oghref_model: ^5.0.0
dev_dependencies: 
  flutter_lints: ^5.0.0
