name: oghref_material
description: Material themed widget for generating rich information link from URL.
version: 1.1.4
repository: https://github.com/rk0cc/oghref/tree/main/widgets/material
issue_tracker: https://github.com/rk0cc/oghref/issues
screenshots:
  - description: Screenshot of OgHref Material example
    path: screenshots/oghref_material.png
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'
dependencies: 
  flutter:
    sdk: flutter
  oghref_builder: ^2.0.4
  oghref_media_control: ^3.0.4
  oghref_model: ^2.0.5
  meta: ^1.9.1
  media_kit: ^1.1.10+1
dev_dependencies: 
  flutter_lints: ^3.0.1
flutter: 