name: oghref_material
description: Material themed widget for generating rich information link from URL.
version: 2.1.0
repository: https://github.com/rk0cc/oghref/tree/main/widgets/material
issue_tracker: https://github.com/rk0cc/oghref/issues
screenshots:
  - description: Screenshot of OgHref Material 3 example
    path: screenshots/oghref_material.png
  - description: Screenshot of OgHref Material 2 example
    path: screenshots/oghref_material_m2.png
funding:
  - https://github.com/sponsors/rk0cc
topics:
  - web
  - link
  - graph
  - http
  - material
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'
dependencies: 
  flutter:
    sdk: flutter
  oghref_builder: ^4.1.2
  oghref_media_control: ^4.0.1
  oghref_model: ^3.5.1
  meta: ^1.9.1
  page_view_dot_indicator: ^2.3.0
  media_kit: ^1.1.10+1
dev_dependencies: 
  flutter_lints: ^3.0.1
flutter: 