name: oghref_material_example
description: Example project of material themed OgHref widgets
publish_to: 'none' 
version: 1.0.0
environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  oghref_material:
    path: ../
  provider: ^6.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
