name: oghref_material_example
description: Example project of material themed OgHref widgets
publish_to: 'none' 
version: 1.0.0
environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  oghref_material:
    path: ../
  provider: ^6.0.5
  media_kit_libs_video: ^1.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
