name: oghref_cupertino
description: Cupertino themed widget for generating rich information link from URL.
version: 2.1.1
repository: https://github.com/rk0cc/oghref/tree/main/widgets/cupertino
issue_tracker: https://github.com/rk0cc/oghref/issues
funding:
  - https://github.com/sponsors/rk0cc
screenshots:
  - description: Screenshot of OgHref Cupertino example
    path: screenshots/oghref_cupertino.png
topics:
  - web
  - link
  - graph
  - http
  - apple
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'
dependencies: 
  flutter:
    sdk: flutter
  oghref_builder: ^4.1.3
  oghref_media_control: ^4.0.1
  oghref_model: ^3.5.2
  meta: ^1.12.0
  media_kit: ^1.1.10+1
  cupertino_icons: ^1.0.8
  page_view_dot_indicator: ^2.3.0
dev_dependencies: 
  flutter_lints: ^4.0.0
flutter: 