name: oghref_builder
description: A Flutter widget for displaying rich information link with callback action provided.
version: 5.0.0
repository: https://github.com/rk0cc/oghref/tree/main/builder
issue_tracker: https://github.com/rk0cc/oghref/issues
funding:
  - https://github.com/sponsors/rk0cc
environment:
  sdk: ^3.8.0
  flutter: '>=3.32.0'
resolution: workspace
dependencies: 
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2
  oghref_model: ^5.0.0
  meta: ^1.15.0
  url_launcher_platform_interface: ^2.3.2
  http: ^1.5.0
dev_dependencies: 
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
