name: oghref_builder
description: A Flutter widget for displaying rich information link with callback action provided.
version: 3.0.1
repository: https://github.com/rk0cc/oghref/tree/main/builder
issue_tracker: https://github.com/rk0cc/oghref/issues
funding:
  - https://github.com/sponsors/rk0cc
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'
dependencies: 
  flutter:
    sdk: flutter
  url_launcher: ^6.1.14
  oghref_model: ^2.1.0
  meta: ^1.9.1
dev_dependencies: 
  flutter_lints: ^3.0.0
flutter: 
