name: oghref_builder
description: A Flutter widget for displaying rich information link with callback action provided.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ^3.10.0
dependencies: 
  flutter:
    sdk: flutter
  url_launcher: ^6.1.14
  oghref_model: '>=1.0.0-beta.2 <2.0.0'
  async: ^2.11.0
dependency_overrides:
  oghref_model:
    path: ../model
flutter: 
