name: oghref_fluent_example
description: Example project of Fluent themed OgHref widgets
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.8.1
  oghref_fluent:
    path: ../
  provider: ^6.1.1
  fluentui_system_icons: ^1.1.222
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
