name: oghref_cupertino_example
description: Example project of Cupertino themed OgHref widgets
publish_to: 'none'
version: 1.1.0
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  oghref_cupertino:
    path: ../
  provider: ^6.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
