name: Widget test (Builder)
on: 
  push: 
    branches: 
      - main
    paths: 
      - 'builder/**/*.dart'
      - .github/workflows/builder_test.yml
  pull_request:
    branches: 
      - main
jobs:
  test:
    name: Widget test
    env:
      working-directory: './builder'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdkver:
          - '3.x'
          - '3.0.x'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ matrix.sdkver }}
      - name: Get dependencies
        working-directory: ${{ env.working-directory }}
        run: flutter pub get
      - name: Perform test
        working-directory: ${{ env.working-directory }}
        run: flutter test .
  