name: Widget test (Builder)
on: 
  push: 
    branches: 
      - main
    paths: 
      - 'builder/**/*.dart'
      - .github/workflows/builder_test.yml
  pull_request:
    branches: 
      - main
jobs:
  test:
    name: Widget test
    env:
      working-directory: './builder'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dart
        uses: dart-lang/setup-dart@v1
      - name: Get dependencies
        working-directory: ${{ env.working-directory }}
        run: dart pub get
      - name: Perform test
        working-directory: ${{ env.working-directory }}
        run: dart test
  